pipeline {
    agent any

    stages {
        stage('checkout_script') {
            steps {
                git changelog: false, credentialsId: '46d318e0-7de7-49ab-86ae-1669225823c1', poll: false, url: 'https://github.com/vekatkriish/apigee.git'
            }
        }
        stage('resolve_task') {
            steps {
                echo 'Resolving'
                echo 'env.fmtId'

            }
        }
    }
    post {
        success {
            script{
                dir ('RallyBuild') {
                    sh 'python updateTask.py $fmtId $notes $BUILD_URL'
                }
                sh env.notes
            script{
                mail (to: env.notes,
                     subject: "Job '{$JOB_NAME}' ({$BUILD_NUMBER}) is sucesses",
                    body: "if you want to check the status please see to {$BUILD_URL}.");
            }
            }
        }
        failure {
            echo 'failed build'
        }
    }
}